### ISSUE TITLE
Choose home page assets/stats

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/datahub#117] opened 2019-04-23 09:10 UTC
What categories/stats do we need on the home page?

**Comment by jonparsonsjncc** [comment] 2019-05-30 09:06
Discuss with comms - Kirsty - or raise in next web meeting

**Comment by jonparsonsjncc** [comment] 2019-06-13 08:24
Closing as duplicate of #140

**Closed** 2019-06-13 08:24 UTC
